#!/usr/bin/env bash
# =============================================================================
# One-time initialisation of a production site on the host that runs it
# (Hetzner site host or an on-premise edge server at the plant).
#
#   sudo bash /srv/mittelconnect/app/scripts/site_init.sh <site-name>
#
# Creates under MC_SITE_DIR (default /srv/mittelconnect/site):
#   secrets/master.key   new Fernet master key, generated on this host (0400, uid 10001)
#   config.yaml          copy of the repository config.yaml to adapt to the plant
#   .env                 ENC[...] credentials entered here, never typed into a shell
#                        history or passed on a command line (0640, root:operator)
#   data/  certs/        outbox / dead letters / heartbeat, and customer CA bundles
#
# The images must exist (scripts/deploy.sh builds them before calling this).
# Refuses to run when a master key already exists, so encrypted values and the
# outbox are never orphaned.
# =============================================================================
set -euo pipefail

SITE_NAME="${1:-}"
APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SITE_DIR="${MC_SITE_DIR:-/srv/mittelconnect/site}"
IMAGE="${MC_IMAGE:-mittelconnect:1.0.0}"
APP_UID=10001
OPERATOR="${SUDO_USER:-root}"
OPERATOR_GROUP="${MC_OPERATOR_GROUP:-$(id -gn "$OPERATOR")}"

die() { echo "ERROR: $*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "run with sudo (needs to set file ownership for uid $APP_UID)"
[[ "$SITE_NAME" =~ ^[a-z0-9][a-z0-9-]{1,30}[a-z0-9]$ ]] \
  || die "usage: $0 <site-name>  (3-32 lowercase letters, digits, dashes)"
command -v docker > /dev/null || die "docker is not installed"
command -v openssl > /dev/null || die "openssl is not installed"
docker image inspect "$IMAGE" > /dev/null 2>&1 || die "image $IMAGE not found; run scripts/deploy.sh first"
[ -f "$SITE_DIR/secrets/master.key" ] && die "$SITE_DIR/secrets/master.key exists; site already initialised"

# Host facts written by cloud-init on Hetzner hosts; absent on edge servers.
MCMON_BIND="127.0.0.1"
if [ -r /etc/mittelconnect/host.env ]; then
  # shellcheck disable=SC1091
  . /etc/mittelconnect/host.env
  if [ -n "${MC_SITE_NAME:-}" ] && [ "$MC_SITE_NAME" != "$SITE_NAME" ]; then
    die "this host was provisioned for site '$MC_SITE_NAME', not '$SITE_NAME'"
  fi
fi

echo "==> Initialising site '$SITE_NAME' in $SITE_DIR"
umask 077
install -d -m 0750 -o root -g "$OPERATOR_GROUP" "$SITE_DIR"
install -d -m 0711 -o "$APP_UID" -g "$APP_UID" "$SITE_DIR/secrets"
install -d -m 0700 -o "$APP_UID" -g "$APP_UID" "$SITE_DIR/data"
install -d -m 0755 -o root -g root "$SITE_DIR/certs"

echo "==> Generating master key on this host"
docker run --rm --network none "$IMAGE" generate-key \
  > "$SITE_DIR/secrets/master.key.tmp"
[ -s "$SITE_DIR/secrets/master.key.tmp" ] || die "key generation produced no output"
mv "$SITE_DIR/secrets/master.key.tmp" "$SITE_DIR/secrets/master.key"
chown "$APP_UID:$APP_UID" "$SITE_DIR/secrets/master.key"
chmod 0400 "$SITE_DIR/secrets/master.key"

encrypt() {
  # The secret travels over stdin only; the key is mounted read-only.
  printf '%s' "$1" | docker run --rm -i --network none --user "$APP_UID:$APP_UID" \
    -v "$SITE_DIR/secrets/master.key:/run/secrets/mittelconnect_master.key:ro" \
    "$IMAGE" encrypt-secret --stdin
}

ask_secret() {
  # Prompts twice without echo; an empty answer means "not used at this site".
  local label="$1" first second
  while true; do
    read -r -s -p "$label (leave empty if not used): " first; echo >&2
    [ -z "$first" ] && { printf ''; return; }
    read -r -s -p "Repeat: " second; echo >&2
    [ "$first" = "$second" ] && { printf '%s' "$first"; return; }
    echo "Values do not match, try again." >&2
  done
}

enc_or_empty() {
  if [ -n "$1" ]; then encrypt "$1"; fi
}

echo "==> Enter the site credentials (input is hidden)"
MSSQL_PW="$(ask_secret 'MS SQL Server password for the read-only login')"
ORACLE_PW="$(ask_secret 'Oracle password for the read-only user')"
SAP_SECRET="$(ask_secret 'SAP OAuth2 client secret')"
SAP_PW="$(ask_secret 'SAP communication user password (basic auth)')"
[ -n "$MSSQL_PW$ORACLE_PW" ] || die "at least one source database password is required"
[ -n "$SAP_SECRET$SAP_PW" ] || die "an SAP client secret or communication user password is required"
PSEUDO_KEY="$(openssl rand -hex 32)"

ENV_TMP="$(mktemp "$SITE_DIR/.env.XXXXXX")"
trap 'rm -f "$ENV_TMP"' EXIT
{
  echo "# MittelConnect site settings, generated by scripts/site_init.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "MC_SITE_NAME=$SITE_NAME"
  echo "MC_SITE_DIR=$SITE_DIR"
  echo "MC_SOURCE_TZ=Europe/Berlin"
  echo "MC_LOG_LEVEL=INFO"
  echo "MC_HEALTH_MAX_AGE_SECONDS=600"
  echo "MCMON_BIND=$MCMON_BIND"
  echo "MCMON_PORT=9464"
  echo "MC_MSSQL_PASSWORD_ENC=$(enc_or_empty "$MSSQL_PW")"
  echo "MC_ORACLE_PASSWORD_ENC=$(enc_or_empty "$ORACLE_PW")"
  echo "MC_SAP_CLIENT_SECRET_ENC=$(enc_or_empty "$SAP_SECRET")"
  echo "MC_SAP_PASSWORD_ENC=$(enc_or_empty "$SAP_PW")"
  echo "MC_PSEUDONYMIZATION_KEY_ENC=$(encrypt "$PSEUDO_KEY")"
} > "$ENV_TMP"
unset MSSQL_PW ORACLE_PW SAP_SECRET SAP_PW PSEUDO_KEY
chown "root:$OPERATOR_GROUP" "$ENV_TMP"
chmod 0640 "$ENV_TMP"
mv "$ENV_TMP" "$SITE_DIR/.env"
trap - EXIT

if [ ! -f "$SITE_DIR/config.yaml" ]; then
  install -m 0644 -o root -g "$OPERATOR_GROUP" "$APP_DIR/config.yaml" "$SITE_DIR/config.yaml"
fi

cat <<EOF

==> Site '$SITE_NAME' initialised.

Next steps:
  1. Back up $SITE_DIR/secrets/master.key OFFLINE now (password manager or
     sealed USB stick in the safe). Without it the .env values and any parked
     outbox records cannot be decrypted.
  2. Adapt $SITE_DIR/config.yaml to the plant: database hosts, SAP base_url,
     allowed_host_suffixes, jobs and mappings. Remove the database entries
     and jobs this site does not use.
  3. From your workstation run:  scripts/deploy.sh <ssh-target>
     It validates the configuration and starts the stack.
EOF
